<?php


/**
 * Implements hook_theme().
 */
function signin_popup_theme(){
  return [
    'join_now_block' => [
      'variables' => [
        'title' => 'Default title',
        'is_anonymous' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function signin_popup_preprocess_field(&$variables){
  if ($variables['element']['#bundle'] == 'cta_block') {
    if ($variables['field_name'] == 'field_cta_block_url') {
      /** @var \Drupal\node\Entity\Node $entity */
      $entity = $variables['element']['#object'];
      $style = $entity->get('field_cta_block_style')->value;
      $variables['attributes']['data-style'] = $style;
    }
  }
}
