<?php
/**
 * @file
 * contains hooks and custom functions.
 */

/**
 * Implements hook_token_info().
 */
function drupalam_customization_token_info() {
  $types['translatable-string'] = array(
    'name' => t("Translatable string"),
    'description' => t("Translatable strings defined for sitewide used."),
  );
  return array(
    'types' => $types,
  );
}

/**
 * Implements hook_tokens().
 */
function drupalam_customization_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  $replacements = array();

  if ($type == 'translatable-string') {
    foreach ($tokens as $name => $original) {
      $replacements[$original] = t($name)->__toString();
    }
  }
  
  return $replacements;
}
